apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-e405a582132e400598da70983f7afe00-depl
  labels:
    app: coll-e405a582132e400598da70983f7afe00
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-e405a582132e400598da70983f7afe00
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-e405a582132e400598da70983f7afe00
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-e405a582132e400598da70983f7afe00
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-e405a582132e400598da70983f7afe00
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping